#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Motor,  motorA,          leftBallCollector, tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorB,          rightBallCollector, tmotorNormal, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,          topBallCollector, tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     frontLeftWheel, tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     frontRightWheel, tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     backRightWheel, tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     backLeftWheel, tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     leftArm,       tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     rightArm,      tmotorNormal, PIDControl, reversed, encoder)
#pragma config(Servo,  srvo_S1_C4_1,    leftClaw,             tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    rightClaw,            tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    door,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"


void drive (int auto_command, long time) {
  int left_wheelsPower;
  int right_wheelsPower;
  int WHEELSPEED = 100;

  if(auto_command==0) {
    //Check for forward movement
    left_wheelsPower=WHEELSPEED;
    right_wheelsPower=WHEELSPEED;
  }else if(auto_command==4) {
    //Check for backwards movement
    left_wheelsPower=-WHEELSPEED;
    right_wheelsPower=-WHEELSPEED;
  }else if(auto_command==2) {
    //Check for right movement
    left_wheelsPower=WHEELSPEED;
    right_wheelsPower=0;
  }else if(auto_command==6) {
    //Check for left movement
    left_wheelsPower=0;
    right_wheelsPower=WHEELSPEED;
  }else if(auto_command==65535) {
    //Do not move
    left_wheelsPower=0;
    right_wheelsPower=0;
    time = 0;
  }else {
    //Do not move
    left_wheelsPower=0;
    right_wheelsPower=0;
  }

  //Drive Code
  motor[frontLeftWheel] = left_wheelsPower;
  motor[backLeftWheel] = left_wheelsPower;
  motor[frontRightWheel] = right_wheelsPower;
  motor[backRightWheel] = right_wheelsPower;
  wait1Msec(time);
  motor[frontLeftWheel] = 0;
  motor[backLeftWheel] = 0;
  motor[frontRightWheel] = 0;
  motor[backRightWheel] = 0;
  return;
}

task main(){

  waitForStart();

  servo[door] = 0;

drive(4,3237);
drive(65535,703);
drive(2,518);
drive(65535,141);
drive(6,1125);
drive(65535,699);
drive(6,847);
drive(65535,799);
drive(4,1031);
drive(65535,232);
drive(6,609);
drive(65535,140);
drive(4,518);
drive(65535,141);
drive(6,1688);
drive(65535,238);
drive(4,420);
drive(65535,185);
drive(6,566);
drive(65535,795);
drive(4,2628);
drive(65535,700);//originally 1360, changed b/c otherwise over 30sec by .282sec
drive(0,703);
drive(65535,144);
drive(6,794);
drive(65535,141);
drive(4,2114);
drive(65535,137);
drive(6,659);
drive(65535,140);
drive(4,6708);

}
