#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Motor,  mtr_S1_C1_1,     frontLeftWheel, tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     frontRightWheel, tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     backRightWheel, tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     backLeftWheel, tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     leftArm,       tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     rightArm,      tmotorNormal, PIDControl, encoder)
#pragma config(Servo,  srvo_S1_C4_1,    leftClaw,             tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    rightClaw,            tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


#include "JoystickDriver.c"

void drive (string auto_command, int time) {
  int left_wheelsPower;
  int right_wheelsPower;

  int WHEELSPEED = 100;

	if(auto_command=="rpoint") {
    //Check for right movement
		//Right Point Turn -- Move right tread backwards, left tread forwards
		left_wheelsPower=WHEELSPEED;
		right_wheelsPower=-WHEELSPEED;
	}else if(auto_command=="lpoint") {
		//Check for left movement
		//Left Point Turn -- Move right tread forwards, left tread backwards
		left_wheelsPower=-WHEELSPEED;
		right_wheelsPower=WHEELSPEED;
	}else if(auto_command=="up") {
		//Check for up movement
		//Forward -- Move both treads forwards
		left_wheelsPower=WHEELSPEED;
		right_wheelsPower=WHEELSPEED;
	}else if(auto_command=="down") {
		//Check for down movement
		//Backward -- Move both treads backwards
		left_wheelsPower=-WHEELSPEED;
		right_wheelsPower=-WHEELSPEED;
	}else if(auto_command=="rswing") {	//SWING TURN RIGHT
		left_wheelsPower=WHEELSPEED;
		right_wheelsPower=0;
	}else if(auto_command=="lswing") {	//SWING TURN LEFT
		left_wheelsPower=0;
		right_wheelsPower=WHEELSPEED;
	}else if(auto_command=="lswingback") {	//SWING TURN BACKWARDS LEFT
		left_wheelsPower=0;
		right_wheelsPower=-WHEELSPEED;
	}else if(auto_command=="rswingback") {	//SWING TURN BACKWARDS RIGHT
		left_wheelsPower=-WHEELSPEED;
		right_wheelsPower=0;
	}else {
		//Do not move
		left_wheelsPower=0;
		right_wheelsPower=0;
	}

//Drive Code
	motor[frontLeftWheel] = left_wheelsPower;
	motor[backLeftWheel] = left_wheelsPower;
	motor[frontRightWheel] = right_wheelsPower;
	motor[backRightWheel] = right_wheelsPower;
	wait1Msec(time);
	motor[frontLeftWheel] = 0;
	motor[backLeftWheel] = 0;
	motor[frontRightWheel] = 0;
	motor[backRightWheel] = 0;
	return;
}




task main(){
    waitForStart();
    motor[backLeftWheel] = -100;
    motor[backRightWheel] = -100;
    motor[frontLeftWheel] = -100;
    motor[frontRightWheel] = -100;
    wait1Msec(2000);

}
