#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Motor,  motorA,          frontTread,    tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorB,          backTread,     tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     frontLeftWheel, tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     frontRightWheel, tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     backLeftWheel, tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     backRightWheel, tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     leftArm,       tmotorNormal, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     rightArm,      tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    leftClaw,             tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    rightClaw,            tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task main(){

  //-----------Constants------------------
  #define WHEELSPEED = 75;
  #define ARMSPEED = 20;
  #define TREADSPEED = 20;
  #define LCLAWOPEN = 127;
  #define LCLAWCLOSE = 255;
  #define RCLAWOPEN = 128;
  #define RCLAWCLOSE = 0;
  //--------------------------------------
  // when give your motors/servos values, use these constants, not numbers
  // so that if we need to change them, they're easy to access

  while(true){

    getJoystickSettings(joystick);

    //------------Driving-----------------

    //Primary Objective:
    //     - Make robot go forward/backward/point-turn when
    //       the left joystick is pushed up/down/left/right.
    //     - Wheel speeds should be set as WHEELSPEED.
    //     - When nothing is pushed, wheels should stop.
    //     - Make sure to create a 5 unit deadzone around the joystick
    //       (the joystick doesn't always center exactly on 0)
    //     - all wheels should be slaved to the front-left wheel
    //
    //Secondary Objective:
    //     - Make robot swing-turn when left joystick is pushed
    //       diagonally (ie. pushed into a corner)

    //------------------------------------
		int wheels_x1;
		int wheels_y1;
		int left_wheelsPower;
		int right_wheelsPower;
		
		wheels_x1 = joystick.joy1_x1; //x-value = left-right movement
		wheels_y1 = joystick.joy1_y1; //y-value = up-down movmeent
		
		/*RANGES OF MOTION - is this a good system?
			Take grid of joystick x-values and y-values, split into twelve 30 degree triangles
			Test to see which triangle values fall in
			Depending on triangle, move forwards/backwards/point turn/swing turn
		*/
		
		
		//If NOT forward/backward/point turn, then swing turn
		
			//Forward - y-value greater than 10, x-value between 10 and -10
		
			//Backward - y-value less than -10, x-value between 10 and -10
		
			//Point Turn Left
		
			//Point Turn Right
		
		//Swing Turn Left
		
		//Swing Turn Right
		
		
		//Cancel out Joystick
		
		
		//Drive Code
		motor[driveLFront] = left_wheelsPower;
		motor[driveLBack] = left_wheelsPower;
		motor[driveRFront] = right_wheelsPower;
		motor[driveRBack] = right_wheelsPower;
		
    //------------Arms--------------------

    //Primary Objective:
    //     - raise arm while btn 5 pressed, lower arm while btn 6 pressed
    //     - when neither btn 5 or 6 is pressed, arm should stop
    //     - arm speed should be set as ARMSPEED
    //     - the right arm should be slaved to the left arm
    //
    //Secondary Objective:
    //     - see if you can find a way to get the arms to rotate to a predetermined position and then stop

    //------------------------------------


    //-----------Claws--------------------

    //Primary Objective:
    //     - close claws when btn 7 pressed, open claws when btn 8 pressed (claws should start open)
    //     - opening positions for left/right claws are LCLAWOPEN and RCLAWOPEN
    //     - closing positions for left/right claws are LCLAWCLOSE and RCLAWCLOSE

    //------------------------------------


    //-----------Tread--------------------

    //Primary Objective:
    //     - if btn 1 is pressed, have tread move forward until btn 2 is pressed.
    //     - tread should move at speed TREADSPEED

    //------------------------------------
  }
}
