#pragma config(Hubs,  S1, HTServo,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,                    sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C2_1,     motor1,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motor2,        tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    servo2,               tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//This is motor configuration, done automatically

#include "JoystickDriver.c" //needed for joystick control

task main(){
  //This tutorial assumes you at least have an understanding of programming,
  //and/or you read the other file about basic programming elements.

  //First off, some basic syntax

#define NOT_A_VARIABLE 10 //creates a constant, which cannot change value. EVAR.

  int integer=1;          //creates an integer, with a starting value of 1

  bool truefalse=true;    //creates a Boolean variable(can have a true/false value), with starting value of true

  float anynumber=3.14;   //creates a float, which can have a decimal, unlike an int

  string words="42bacon"; //creates a string, which can contain words, characters, etc.

  //Now, onto the specific things

  while(true){                      //It keeps going and going...
    getJoystickSettings(joystick);  //gets new input from the joystick. You'll wanna put this in the while(true) loop

    if(joy1Btn(1)==1){
      //If button 1 is pressed, it will execute this block of code.
      //Syntax is joy1Btn(x), where x is the corresponding number between 1 and 10
      motor[motor1]=100;
      //sets the power of motor1 to 100. Power can be anything between -100 and 100
      //The motor command sets the power of the motor, aka the speed it runs at
      }

    servo[servo1]=joy1_y1+100;
    //Sets the position of servo1 to the y coordinate of the left joystick
    //joy1_y1 and joy1_x1 are the values of the left joystick,
    //joy1_y2 and joy1_x2 are the values of the right joystick
    //The servo can be at any position between 0 and 255, measured in degrees
    //The joystick registers between -100 and 100, so some math is needed
    //The joystick is also imprecise about zeroing out, and so usually some cancelling-out
    //function is needed, like the one below

    int motorSpeed;
    motorSpeed=joy1_y1;
    if(abs(motorSpeed)<10){
      motorSpeed=0;
    }

    motor[motor2]=motorSpeed;

    //Zeroes out the joystick, so that when not pressed, will stay at 0

    //Yeah, that's the brunt of the code
    //There's some extra stuff for sensors, but this all we need to work with for now
  }

}
