#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,                    sensorI2CMuxController)
#pragma config(Motor,  motorA,          leftBallCollector, tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorB,          rightBallCollector, tmotorNormal, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,          topBalllCollector, tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     frontLeftWheel, tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     frontRightWheel, tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     backRightWheel, tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     backLeftWheel, tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     leftArm,       tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     rightArm,      tmotorNormal, PIDControl, reversed, encoder)
#pragma config(Servo,  srvo_S1_C4_1,    leftClaw,             tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    rightClaw,            tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    door,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

//-----------Constants------------------
#define WHEELSPEED 100
#define ARMSPEED 30
#define LCLAWOPEN 0
#define LCLAWCLOSE 128
#define RCLAWOPEN 255
#define RCLAWCLOSE 127
#define DOOROPEN 255
#define DOORCLOSE 128

//--------------------------------------
// when give your motors/servos values, use these constants, not numbers
// so that if we need to change them, they're easy to access

void initialize()
{
  motor[frontLeftWheel] = 0;
  motor[frontRightWheel] = 0;
  motor[backLeftWheel] = 0;
  motor[backRightWheel] = 0;
  motor[leftArm] = 0;
  motor[rightArm] = 0;
  nMotorEncoder[rightArm] = 0;
  //nMotorEncoderTarget[rightArm] = 10;
  servo[leftClaw] = LCLAWOPEN;
  servo[rightClaw] = RCLAWOPEN;
  servo[door] = DOORCLOSE;

  string BatteryLevel = externalBatteryAvg;

  nxtDisplayCenteredBigTextLine (3, BatteryLevel);
}

int toggle(bool buttoned, int spin, int direction)
{
  if(!buttoned)
    if(spin == 0)
      return direction;
    else
      return 0;
  else
    return spin;
}

task main()
{
  initialize();
  bool buttoned = false;
  int spin = 0;

  waitForStart();

  //Used for calculating size of triangle of motion that will define point turning left/right
  float tan_angle_leftright = 1.0 / sqrt(3); // tan(PI / 6), Graph of y=tan(angle_leftright) used for point turn left/right; MUST BE IN RADIANS

  //Used for calculating size of triangle of motion that will define moving forward/back
  float tan_angle_updown = sqrt(3);          // tan(PI / 3), Graph of y=tan(angle_updown) used for forward/back; MUST BE IN RADIANS

  while (true) {

    getJoystickSettings(joystick);

    //------------Driving-----------------

    //Primary Objective:
    //     - Make robot go forward/backward/point-turn when
    //       the left joystick is pushed up/down/left/right.
    //     - Wheel speeds should be set as WHEELSPEED.
    //     - When nothing is pushed, wheels should stop.
    //     - Make sure to create a 5 unit deadzone around the joystick
    //       (the joystick doesn't always center exactly on 0)
    //     - all wheels should be slaved to the front-left wheel
    //
    //Secondary Objective:
    //     - Make robot swing-turn when left joystick is pushed
    //       diagonally (ie. pushed into a corner)

    int wheels_x1 = 0;
    int wheels_y1 = 0;
    int left_wheelsPower = 0;
    int right_wheelsPower = 0;

    wheels_x1 = joystick.joy1_x2;	//x-value = left-right joystick movement
    wheels_y1 = joystick.joy1_y2;	//y-value = up-down joystick movmeent

    float tan_line_updown = tan_angle_updown * wheels_x1;
    float tan_line_leftright = tan_angle_leftright * wheels_x1;

    /*RANGES OF MOTION
    Take grid of joystick x-values and y-values, split into twelve 30 degree triangles
    Use graphs of y=tan(30)x, y=-tan(30)x, y=tan(60)x, y=-tan(60)x  -
    To alter sizes of triangles, change the degree (e.g. tan(45))
    Test to see which triangle values fall in
    Depending on triangle, move forwards/backwards/point turn/swing turn
    */

    if (abs(wheels_x1) > 10 && abs(wheels_y1) > 10) {	//If in deadzone, ignore movement - no need to run useless code
      if (wheels_y1 <= tan_line_leftright) {
        //Must be either Right Point, Right Back Swing, Backwards, or Left Back Swing
        //!IMPORTANT: Code works by order, so code CANNOT be merged unless order is followed
        if (wheels_y1 >= -tan_line_leftright) {
          //Point Turn Right
          left_wheelsPower = WHEELSPEED;
          right_wheelsPower = -WHEELSPEED;
	    	}else if (wheels_y1 >= -tan_line_updown) {
          //Swing Turn Backwards Right
          left_wheelsPower = -WHEELSPEED;
          right_wheelsPower = 0;
        } else if (wheels_y1 <= tan_line_updown) {
          //Backward -- Move both treads backwards
          left_wheelsPower = -WHEELSPEED;
          right_wheelsPower = -WHEELSPEED;
        } else {
          //Swing Turn Backwards Left
          left_wheelsPower = 0;
          right_wheelsPower = -WHEELSPEED;
        }
      } else {
        //Must be either Left Point, Left Swing, Forwards, or Right Swing
        //!IMPORTANT: Code works by order, so code CANNOT be merged unless order is followed
        if (wheels_y1 <= -tan_line_leftright) {
          //Point Turn Left
          left_wheelsPower = -WHEELSPEED;
          right_wheelsPower = WHEELSPEED;
	      }else if (wheels_y1 <= -tan_line_updown) {
          //Swing Turn Left
          left_wheelsPower = 0;
          right_wheelsPower = WHEELSPEED;
        } else if (wheels_y1 >= tan_line_updown) {
          //Forward -- Move both treads forwards
          left_wheelsPower = WHEELSPEED;
          right_wheelsPower = WHEELSPEED;
        } else {
          //Swing Turn Right
          left_wheelsPower = WHEELSPEED;
          right_wheelsPower = 0;
        }
      }
    } else {		 //Joystick is in dead zone - set powers to zero
      left_wheelsPower = 0;
      right_wheelsPower = 0;
    }

    //Drive Code
    motor[frontLeftWheel] = left_wheelsPower;
    motor[backLeftWheel] = left_wheelsPower;
    motor[frontRightWheel] = right_wheelsPower;
    motor[backRightWheel] = right_wheelsPower;

    left_wheelsPower = 0;
    right_wheelsPower = 0;

    //------------------------------------


    //----------Ball Collector------------

    //Primary Objective:
    //     - collect balls by spinning a zip-tied rod.

    if(joy1Btn(4) == 1){
      spin = toggle(buttoned, spin, 100);
      buttoned = true;
    }else if(joy1Btn(2) == 1){
      spin = toggle(buttoned, spin, -100);
      buttoned = true;
    }else
      buttoned = false;

    motor[leftBallCollector] = spin;
    motor[rightBallCollector] = spin;
    motor[topBalllCollector] = spin;

    //------------------------------------


    //------------Arms--------------------

    //Primary Objective:
    //     - raise arm while btn 5 pressed, lower arm while btn 6 pressed
    //     - when neither btn 5 or 6 is pressed, arm should stop
    //     - arm speed should be set as ARMSPEED
    //     - the right arm should be slaved to the left arm
    //
    //Secondary Objective:
    //     - see if you can find a way to get the arms to rotate to a predetermined position and then stop

    if (joy1Btn(5) == 1) {
      //MOVE ARM UP 30% POWER
      motor[leftArm] = -ARMSPEED;
      motor[rightArm] = -ARMSPEED;
    } else if (joy1Btn(6) == 1) {
      //MOVE ARM DOWN 30% POWER
      motor[leftArm] = ARMSPEED;
      motor[rightArm] = ARMSPEED;
    } else {
      //DON'T MOVE ARM
      motor[leftArm] = 0;
      motor[rightArm] = 0;
    }

    //------------------------------------


    //-----------Claws--------------------

    //Primary Objective:
    //     - open claws when btn 1 pressed (claws should start open) (LCLAWOPEN, RCLAWOPEN)
    //     - grab box when btn 2 pressed (LCLAWBOX, RCLAWBOX)
    //     - grab ball when btn 3 pressed (LCLAWBALL, RCLAWBALL)

    if (joy1Btn(7) == 1) {
      //open left claw
      servo[leftClaw] = LCLAWOPEN;
      //open right claw
      servo[rightClaw] = RCLAWOPEN;
    } else if (joy1Btn(8) == 1) {
      //close left claw
      servo[leftClaw] = LCLAWCLOSE;
      //close right claw
      servo[rightClaw] = RCLAWCLOSE;
    }

    //------------------------------------


    //-----------Door---------------------

    //Primary Objective:
    //     - open to admit bowling ball/crate, clos to retrain bowling ball/crate
    //     - Tophat Up to open, Tophat Down to close

    if(joystick.joy1_TopHat == 0){
      //open door
      servo[door] = DOOROPEN;
    }else if(joystick.joy1_TopHat == 4){
      //close door
      servo[door] = DOORCLOSE;
    }

    //------------------------------------
  }
}
