#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,          leftBallCollector, tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorB,          rightBallCollector, tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorC,          topBallCollector, tmotorNormal, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     frontLeftWheel, tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     frontRightWheel, tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     backRightWheel, tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     backLeftWheel, tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     leftArm,       tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     rightArm,      tmotorNormal, PIDControl, reversed, encoder)
#pragma config(Servo,  srvo_S1_C4_1,    leftClaw,             tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    rightClaw,            tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    door,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

//-----------Constants------------------
#define WHEELSPEED 100
#define ARMSPEED 30
#define LCLAWOPEN 0
#define LCLAWCLOSE 128
#define RCLAWOPEN 255
#define RCLAWCLOSE 127
#define DOOROPEN 255
#define DOORCLOSE 128

//--------------------------------------
// when give your motors/servos values, use these constants, not numbers
// so that if we need to change them, they're easy to access

void initialize()
{
  motor[frontLeftWheel] = 0;
  motor[frontRightWheel] = 0;
  motor[backLeftWheel] = 0;
  motor[backRightWheel] = 0;
  motor[leftArm] = 0;
  motor[rightArm] = 0;
  nMotorEncoder[rightArm] = 0;
  servo[leftClaw] = LCLAWOPEN;
  servo[rightClaw] = RCLAWOPEN;
  servo[door] = DOORCLOSE;

  string BatteryLevel = externalBatteryAvg;

  nxtDisplayCenteredBigTextLine (3, BatteryLevel);
}

int toggle(bool buttoned, bool condition)
{
  if(!buttoned)
    return !condition;
  else
    return condition;
}

task main()
{
  initialize();
  bool fourButtoned = false;
  bool tenButtoned = false;
  bool spin = false;
  bool driveForward = true;
  int armspeed = ARMSPEED;

  waitForStart();

  while (true) {

    getJoystickSettings(joystick);

    //------------Driving-----------------

    //Primary Objective:
    //     - Make robot go forward/backward/point-turn when
    //       the left joystick is pushed up/down/left/right.
    //     - Wheel speeds should be set as WHEELSPEED.
    //     - When nothing is pushed, wheels should stop.
    //     - Make sure to create a 5 unit deadzone around the joystick
    //       (the joystick doesn't always center exactly on 0)
    //     - all wheels should be slaved to the front-left wheel
    //
    //Secondary Objective:
    //     - Make robot swing-turn when left joystick is pushed
    //       diagonally (ie. pushed into a corner)

    if (joy1Btn(10)==1){
      driveForward = toggle(tenButtoned, driveForward);
      PlayTone(220, 1);
    }
    tenButtoned = joy1Btn(10);

    int wheels_x1 = 0;
    int wheels_y1 = 0;
    int left_wheelsPower = 0;
    int right_wheelsPower = 0;

    wheels_x1 = joystick.joy1_x2;	//x-value = left-right joystick movement
    wheels_y1 = joystick.joy1_y2;	//y-value = up-down joystick movmeent

    float tan_line_updown = wheels_x1+10;
    float tan_line_leftright = wheels_x1-10;

    /*RANGES OF MOTION
    Take grid of joystick x-values and y-values, split into twelve divisions by an box-letter x
    Use graphs of y=x+10, y=x-10, y=-(x+10), y=-(x-10)  -
    To alter sizes of divisions, change the degree (e.g. tan(45))
    Test to see which division the values fall in
    Depending on division, move forwards/backwards/point turn/swing turn
    */

    if (abs(wheels_x1) > 10 && abs(wheels_y1) > 10) {	//If in deadzone, ignore movement - no need to run useless code
      if (wheels_x1 > 0) {
        //Must be either Forward, Right Forward Swing, Right Point, Right Backward Swing, or Backward
        //!IMPORTANT: Code works by order, so code CANNOT be merged unless order is followed
        if (wheels_y1 >= tan_line_updown) {
          //Forward
          left_wheelsPower = WHEELSPEED;
          right_wheelsPower = WHEELSPEED;
	    	}else if (wheels_y1 >= tan_line_leftright) {
          //Swing Turn Right Forward
	    	  left_wheelsPower = WHEELSPEED;
          right_wheelsPower = 0;
        } else if (wheels_y1 >= -tan_line_leftright) {
          //Point Turn Right
          left_wheelsPower = WHEELSPEED;
          right_wheelsPower = -WHEELSPEED;
        } else if (wheels_y1 >= -tan_line_updown) {
          //Swing Turn Right Backward
	    	  left_wheelsPower = -WHEELSPEED;
          right_wheelsPower = 0;
        } else {
          //Backward
          left_wheelsPower = -WHEELSPEED;
          right_wheelsPower = -WHEELSPEED;
        }
      } else {
        //Must be either Forward, Left Forward Swing, Left Point, Left Backward Swing, or Backward
        //!IMPORTANT: Code works by order, so code CANNOT be merged unless order is followed
        if (wheels_y1 >= -tan_line_leftright) {
          //Forward
          left_wheelsPower = WHEELSPEED;
          right_wheelsPower = WHEELSPEED;
	      }else if (wheels_y1 >= -tan_line_updown) {
          //Swing Turn Left Forward
          left_wheelsPower = 0;
          right_wheelsPower = WHEELSPEED;
        } else if (wheels_y1 >= tan_line_updown) {
          //Point Turn Left
          left_wheelsPower = -WHEELSPEED;
          right_wheelsPower = WHEELSPEED;
        } else if (wheels_y1 >= tan_line_leftright) {
          //Swing Turn Left Backward
          left_wheelsPower = 0;
          right_wheelsPower = -WHEELSPEED;
        } else {
          //Backward
          left_wheelsPower = -WHEELSPEED;
          right_wheelsPower = -WHEELSPEED;
        }
      }
    } else {		 //Joystick is in dead zone - set powers to zero
      left_wheelsPower = 0;
      right_wheelsPower = 0;
    }

    //Drive Code
    if(!driveForward && left_wheelsPower != -right_wheelsPower){
      left_wheelsPower = -left_wheelsPower;
      right_wheelsPower = -right_wheelsPower;
    }

    motor[frontLeftWheel] = left_wheelsPower;
    motor[backLeftWheel] = left_wheelsPower;
    motor[frontRightWheel] = right_wheelsPower;
    motor[backRightWheel] = right_wheelsPower;

    //------------------------------------


    //----------Ball Collector------------

    //Primary Objective:
    //     - collect balls by spinning a zip-tied rod.

    if(joy1Btn(4) == 1){
      spin = toggle(fourButtoned, spin);
    }else if(joy1Btn(2) == 1){
      motor[leftBallCollector] = -100;
      motor[rightBallCollector] = -100;
      motor[topBallCollector] = -100;
    }
    fourButtoned = joy1Btn(4);

    if(spin){
      motor[leftBallCollector] = 100;
      motor[rightBallCollector] = 100;
      motor[topBallCollector] = 100;
    }else{
      motor[leftBallCollector] = 0;
      motor[rightBallCollector] = 0;
      motor[topBallCollector] = 0;
    }

    //------------------------------------


    //------------Arms--------------------

    //Primary Objective:
    //     - raise arm while btn 5 pressed, lower arm while btn 6 pressed
    //     - when neither btn 5 or 6 is pressed, arm should stop
    //     - arm speed should be set as ARMSPEED
    //     - the right arm should be slaved to the left arm
    //
    //Secondary Objective:
    //     - see if you can find a way to get the arms to rotate to a predetermined position and then stop

    if(joy1Btn(5) == 1)
      armspeed = 100;
    else if(joy1Btn(7) == 1)
      armspeed = ARMSPEED;

    if (joy1Btn(6) == 1) {
      //MOVE ARM UP 30% POWER
      motor[leftArm] = -armspeed;
      motor[rightArm] = -armspeed;
    } else if (joy1Btn(8) == 1) {
      //MOVE ARM DOWN 30% POWER
      motor[leftArm] = armspeed;
      motor[rightArm] = armspeed;
    } else {
      //DON'T MOVE ARM
      motor[leftArm] = 0;
      motor[rightArm] = 0;
    }

    //------------------------------------


    //-----------Claws--------------------

    //Primary Objective:
    //     - open claws when btn 1 pressed (claws should start open) (LCLAWOPEN, RCLAWOPEN)
    //     - grab box when btn 2 pressed (LCLAWBOX, RCLAWBOX)
    //     - grab ball when btn 3 pressed (LCLAWBALL, RCLAWBALL)

    /*
    if (joy1Btn(7) == 1) {
      //open left claw
      servo[leftClaw] = LCLAWOPEN;
      //open right claw
      servo[rightClaw] = RCLAWOPEN;
    } else if (joy1Btn(8) == 1) {
      //close left claw
      servo[leftClaw] = LCLAWCLOSE;
      //close right claw
      servo[rightClaw] = RCLAWCLOSE;
    }
    */

    //------------------------------------


    //-----------Door---------------------

    //Primary Objective:
    //     - open to admit bowling ball/crate, clos to retrain bowling ball/crate
    //     - Tophat Up to open, Tophat Down to close

    if(joystick.joy1_TopHat == 0){
      //open door
      servo[door] = DOOROPEN;
    }else if(joystick.joy1_TopHat == 4){
      //close door
      servo[door] = DOORCLOSE;
    }

    //------------------------------------
  }
}
